include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    curly_braces_in_flow_control_structures: true
    always_put_control_body_on_new_line: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
