name: macos_secure_bookmarks
description: Flutter desktop plugin for managing secure bookmarks to access files in sandbox.
version: 0.2.0
homepage: https://github.com/authpass/macos_secure_bookmarks

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SecureBookmarksPlugin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0
  logging_appenders: ^1.0.0
